# 00 — Pipeline Logs Exploration

This notebook explores **all** logs, CSVs and reports produced by the Snakemake pipeline.
Files are mounted at `/pipeline-logs` from the host `./pipeline_logs` directory.

All cells are defensive: missing files are reported without raising exceptions.

## Pipeline execution order covered here

1. [Setup & directory overview](#1-setup)
2. [Metadata downloads & merging — HTML reports](#2-metadata)
3. [Database creation & validation](#3-database)
4. [Host resolution & download](#4-host-download)
5. [Host mapping creation](#5-host-mapping)
6. [Host FASTA QC & indexing](#6-host-qc)
7. [Host status report](#7-host-status)
8. [Phage & protein FASTA merging](#8-fasta-merge)
9. [Phage & protein FASTA indexing](#9-fasta-index)

## Versioning & Provenance in PBI-Scope

PBI uses **three independent layers** to track identity and provenance. Understanding
this is essential before interpreting any pipeline output.

| Layer | What it is | Where it lives | Example |
|-------|-----------|----------------|--------|
| **Package version** | Semantic version of the `pbi` Python library | `src/pbi/__init__.py` → `__version__` | `0.6.0` |
| **Provider schema profile** | Stable label for a data-source's schema/column contract | `workflow/config/config.yaml` → `public_data_provider.schema_profile` | `phagescope_v1` |
| **Pipeline run provenance** | Exact build metadata for one pipeline execution | `/pipeline-logs/csv/pipeline_run_provenance.json` (artifact) | snapshot date, git ref, etc. |

### Why keep them separate?

- The **package version** follows [SemVer](https://semver.org/) and changes whenever the
  `pbi` API or behaviour changes.
- The **schema profile** (`phagescope_v1`) only changes when the upstream data provider
  (PhageScope) modifies its column layout or semantics. It is deliberately stable — you
  can safely compare runs with the same profile even across different package releases.
  Bump it to `phagescope_v2` only when the schema contract changes.
- The **run provenance** captures the exact snapshot date, git commit, and any
  run-specific metadata for a single pipeline execution. It is the traceability record.

> **Tip:** `notebooks/06_reproducibility.ipynb` goes deeper into reading and validating
> all three layers programmatically.

In [1]:
# ---------------------------------------------------------------------------
# Surface version / provenance information at notebook startup
# ---------------------------------------------------------------------------
import sys
import json
from pathlib import Path

# ── pbi package version ──────────────────────────────────────────────────
project_root = Path.cwd().parent
if str(project_root / 'src') not in sys.path:
    sys.path.insert(0, str(project_root / 'src'))
try:
    import pbi as _pbi
    print(f'pbi package version : {_pbi.__version__}')
except ImportError:
    print('pbi package not importable from this environment')

# ── pipeline run provenance (if pipeline has been executed) ───────────────
_prov_path = Path('/pipeline-logs/csv/pipeline_run_provenance.json')
if _prov_path.exists():
    _prov = json.loads(_prov_path.read_text())
    print('\nPipeline run provenance:')
    for _k, _v in _prov.items():
        print(f'  {_k:<40} {_v}')
else:
    print('\nNo pipeline_run_provenance.json found — pipeline may not have run yet.')
    print('  (This is normal when the notebook is opened before running the pipeline.)')

pbi package version : 0.6.0

Pipeline run provenance:
  pipeline_run_timestamp                   2026-09-29T12:01:21Z
  provider_name                            PhageScope
  provider_release                         rolling
  provider_snapshot_date                   2026-07-05
  provider_schema_profile                  phagescope_v2
  provider_api_base_url                    https://phageapi.deepomics.org
  provider_provenance_mode                 config_pinned
  pbi_version
  git_commit
  download_records_count                   229

---
<a id='1-setup'></a>
## 1 — Setup & Directory Overview

In [2]:
from pathlib import Path
import json
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 80)

# ---------------------------------------------------------------------------
# Root path — matches PBI_LOGS_DIR env var inside the Docker container
# ---------------------------------------------------------------------------
logs_root = Path('/pipeline-logs')
logs_dir  = logs_root / 'logs'
csv_dir   = logs_root / 'csv'
rep_dir   = logs_root / 'reports'

print(f'Logs root : {logs_root}  (exists={logs_root.exists()})')
print(f'logs/     : {logs_dir.exists()}')
print(f'csv/      : {csv_dir.exists()}')
print(f'reports/  : {rep_dir.exists()}')

Logs root : /pipeline-logs  (exists=True)
logs/     : True
csv/      : True
reports/  : True

In [3]:
# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

MAX_LOG_LINES = 50  # max lines shown per text log


def show_log(path, max_lines=MAX_LOG_LINES):
    """Print the content of a text log file, or report if unavailable."""
    path = Path(path)
    print(f'\n=== {path} ===')
    if not path.exists():
        print('  (not available yet)')
        return
    if path.stat().st_size == 0:
        print('  (file exists but is empty)')
        return
    try:
        with path.open('r', encoding='utf-8', errors='replace') as fh:
            lines = fh.readlines()
        for line in lines[:max_lines]:
            print(line.rstrip('\n'))
        if len(lines) > max_lines:
            print(f'... ({len(lines) - max_lines} more lines — increase max_lines to see all)')
    except Exception as exc:
        print(f'  Could not read: {exc}')


def load_csv(path, label=None):
    """Load a CSV as a DataFrame and print a short summary."""
    path = Path(path)
    tag = label or path.name
    if not path.exists():
        print(f'[{tag}] not available yet.')
        return pd.DataFrame()
    if path.stat().st_size == 0:
        print(f'[{tag}] exists but is empty.')
        return pd.DataFrame()
    try:
        df = pd.read_csv(path, low_memory=False)
        print(f'[{tag}] {len(df):,} rows × {len(df.columns)} columns')
        return df
    except Exception as exc:
        print(f'[{tag}] could not be loaded: {exc}')
        return pd.DataFrame()


def list_dir(d, indent=2):
    """Print a sorted listing of *d*."""
    d = Path(d)
    if not d.exists():
        print(' ' * indent + '(missing)')
        return
    items = sorted(d.iterdir(), key=lambda p: p.name.lower())
    if not items:
        print(' ' * indent + '(empty)')
        return
    for p in items:
        kind = 'DIR ' if p.is_dir() else 'FILE'
        size = '' if p.is_dir() else f'  {p.stat().st_size:>12,} B'
        print(' ' * indent + f'[{kind}] {p.name}{size}')

In [4]:
# Full recursive listing of /pipeline-logs
print('── pipeline-logs/')
for sub in ('logs', 'csv', 'reports'):
    print(f'   ── {sub}/')
    list_dir(logs_root / sub, indent=6)

── pipeline-logs/
   ── logs/
      [FILE] create_host_mapping.log         2,878 B
      [FILE] create_host_status_report.log         1,104 B
      [FILE] host_download.log    12,057,395 B
      [FILE] host_fasta_qc.csv       538,768 B
      [FILE] index_individual_host_sequences.log           276 B
      [FILE] index_phage_sequences.log         4,377 B
      [FILE] index_protein_sequences.log        69,240 B
      [FILE] makeblastdb_combined.log           331 B
      [FILE] makeblastdb_hosts.log           327 B
      [FILE] makeblastdb_phages.log           316 B
      [FILE] makeblastdb_private.log           325 B
      [FILE] makeblastdb_proteins.log           321 B
      [FILE] merge_phage_fasta.log         2,672 B
      [FILE] merge_protein_fasta.log         2,680 B
   ── csv/
      [FILE] .host_indexes_complete             0 B
      [FILE] assembly_metadata.csv     1,341,795 B
      [FILE] host_bacterial_cache.json        86,447 B
      [FILE] host_metadata.csv       755,204 B
      [FILE] host_token_resolution_cache.json     3,683,341 B
      [FILE] per_source_phage_counts.json           448 B
      [FILE] per_source_protein_counts.json           496 B
      [FILE] phage_host_assemblies.csv   216,485,124 B
      [FILE] phage_host_candidates.csv   129,078,999 B
      [FILE] phage_host_links.csv   157,244,276 B
      [FILE] pipeline_run_provenance.csv           312 B
      [FILE] pipeline_run_provenance.json           391 B
      [FILE] public_data_manifest.csv       151,284 B
      [FILE] public_data_manifest.json       262,789 B
   ── reports/
      [FILE] all_phages_duplicates.html       349,955 B
      [FILE] all_proteins_duplicates.html       352,815 B
      [FILE] annotated_proteins_metadata_report.html     9,724,751 B
      [FILE] antimicrobial_resistance_gene_metadata_report.html     1,611,254 B
      [FILE] crispr_array_metadata_report.html    16,420,469 B
      [FILE] database_validation.html        41,525 B
      [FILE] host_status_report.csv   344,165,827 B
      [FILE] phage_anti_crispr_metadata_report.html     1,286,426 B
      [FILE] phage_metadata_report.html     2,846,212 B
      [FILE] phage_transmembrane_protein_metadata_report.html     9,032,666 B
      [FILE] phage_trna_tmrna_metadata_report.html     2,657,058 B
      [FILE] phage_virulent_factor_metadata_report.html     1,725,919 B
      [FILE] transcription_terminator_metadata_report.html     1,923,061 B

---
<a id='2-metadata'></a>
## 2 — Metadata Downloads & Merging

The pipeline downloads TSVs from PhageScope for each feature and merges them.
A ydata-profiling HTML report is generated per feature.  
No `.log` file is produced at this stage (downloads use `wget` directly via Snakemake shell rules).

> Files live in: `pipeline-logs/reports/{feature}_report.html`

In [5]:
FEATURES = [
    'phage_metadata',
    'annotated_proteins_metadata',
    'transcription_terminator_metadata',
    'phage_trna_tmrna_metadata',
    'phage_anti_crispr_metadata',
    'phage_virulent_factor_metadata',
    'phage_transmembrane_protein_metadata',
    'antimicrobial_resistance_gene_metadata',
    'crispr_array_metadata',
]

print('Metadata report availability:')
for feat in FEATURES:
    p = rep_dir / f'{feat}_report.html'
    status = f'✅  {p.stat().st_size:,} B' if p.exists() else '❌  missing'
    print(f'  {feat:<50} {status}')

Metadata report availability:
  phage_metadata                                     ✅  2,846,212 B
  annotated_proteins_metadata                        ✅  9,724,751 B
  transcription_terminator_metadata                  ✅  1,923,061 B
  phage_trna_tmrna_metadata                          ✅  2,657,058 B
  phage_anti_crispr_metadata                         ✅  1,286,426 B
  phage_virulent_factor_metadata                     ✅  1,725,919 B
  phage_transmembrane_protein_metadata               ✅  9,032,666 B
  antimicrobial_resistance_gene_metadata             ✅  1,611,254 B
  crispr_array_metadata                              ✅  16,420,469 B

The HTML reports can be opened directly in the browser (they are mounted at `./pipeline_logs/reports/`).

---
<a id='3-database'></a>
## 3 — Database Creation & Validation

Rules: `create_duckdb` → `optimize_database` → `validate_database`  
The validation step produces an HTML report summarising table counts and integrity checks.

> File: `pipeline-logs/reports/database_validation.html`

In [6]:
db_report = rep_dir / 'database_validation.html'
if db_report.exists():
    print(f'✅  database_validation.html  ({db_report.stat().st_size:,} B)')
    print('    Open in a browser or use the JupyterLab HTML viewer.')
else:
    print('❌  database_validation.html not available yet.')

✅  database_validation.html  (41,525 B)
    Open in a browser or use the JupyterLab HTML viewer.

---
<a id='4-host-download'></a>
## 4 — Host Resolution & Download

Rule: `download_host_genomes` (script: `download_host_genomes_robust.py`)

This step:
1. Parses each phage's `Host` field into candidate tokens.
2. Resolves tokens to NCBI assembly accessions via `AssemblyResolver`.
3. Downloads genome FASTA files via FTP.

**Log files**
| File | Description |
|------|-------------|
| `logs/host_download.log` | Full execution log (resolver + downloader) |
| `logs/host_download_failures.log` | Per-accession failures only |

**CSV outputs** (in `csv/`)
| File | Description |
|------|-------------|
| `phage_host_candidates.csv` | One row per (Phage_ID, Host_Token) |
| `phage_host_assemblies.csv` | Resolved assembly links with confidence scoring |
| `assembly_metadata.csv` | Download status per assembly |
| `host_metadata.csv` | High-level host metadata |
| `phage_host_links.csv` | Final phage → assembly links |
| `host_token_resolution_cache.json` | Persistent token→assembly cache |

In [7]:
# ── Text logs ──────────────────────────────────────────────────────────────
show_log(logs_dir / 'host_download.log')
show_log(logs_dir / 'host_download_failures.log')

=== /pipeline-logs/logs/host_download.log ===
2026-09-29 12:01:45,463 - INFO - ✅ AssemblyResolver initialized
2026-09-29 12:01:45,463 - INFO -    Email: th.schow@gmail.com
2026-09-29 12:01:45,463 - INFO -    API key: Yes
2026-09-29 12:01:45,463 - INFO -    Delay: 0.1s
2026-09-29 12:01:45,463 - INFO - ✅ RobustHostGenomeDownloader initialized
2026-09-29 12:01:45,463 - INFO -    Phage CSV: /data/intermediate/csv/merged/merged_phage_metadata.csv
2026-09-29 12:01:45,463 - INFO -    Output directory: /data/intermediate/fasta/hosts
2026-09-29 12:01:45,463 - INFO -    Metadata only: False
2026-09-29 12:01:45,463 - INFO -    Skip existing: True
2026-09-29 12:01:45,463 - INFO -    Validate checksums: True
2026-09-29 12:01:45,463 - INFO -    Reuse resolution cache: True
2026-09-29 12:01:45,463 - INFO -    Resolution cache TTL: 120d
2026-09-29 12:01:45,463 - INFO -    Resolution cache file: /pipeline-logs/csv/host_token_resolution_cache.json
2026-09-29 12:01:45,463 - INFO -    Stats timeout: 60.0s, checkpoint every: 100
2026-09-29 12:01:45,463 - INFO - ================================================================================
2026-09-29 12:01:45,463 - INFO - ROBUST HOST GENOME DOWNLOADER
2026-09-29 12:01:45,463 - INFO - ================================================================================
2026-09-29 12:01:45,463 - INFO - 📋 Starting multi-host processing pipeline...
2026-09-29 12:03:04,781 - INFO - ✅ Written 1356533 candidate rows to /pipeline-logs/csv/phage_host_candidates.csv
2026-09-29 12:03:50,043 - INFO - 🔍 Resolving 10778 unique host tokens…
2026-09-29 12:03:50,043 - INFO - [1/10778] Resolving 'Xylella fastidiosa' (species_name)…
2026-09-29 12:03:50,043 - INFO - 🔍 Resolving 'Xylella fastidiosa' (type: species_name)
2026-09-29 12:03:58,433 - INFO -    Found TaxID 2371 for 'Xylella fastidiosa'
2026-09-29 12:03:59,588 - INFO -    ✅ GCF_055959565.1
2026-09-29 12:03:59,588 - INFO - [2/10778] Resolving 'Corynebacterium xerosis' (species_name)…
2026-09-29 12:03:59,589 - INFO - 🔍 Resolving 'Corynebacterium xerosis' (type: species_name)
2026-09-29 12:03:59,894 - INFO -    Found TaxID 1725 for 'Corynebacterium xerosis'
2026-09-29 12:04:00,771 - INFO -    ✅ GCF_055583525.1
2026-09-29 12:04:00,771 - INFO - [3/10778] Resolving 'Salmonella enterica' (species_name)…
2026-09-29 12:04:00,772 - INFO - 🔍 Resolving 'Salmonella enterica' (type: species_name)
2026-09-29 12:04:01,057 - INFO -    Found TaxID 28901 for 'Salmonella enterica'
2026-09-29 12:04:02,097 - INFO -    ✅ GCF_061253545.1
2026-09-29 12:04:02,098 - INFO - [4/10778] Resolving 'Bacillus cereus' (species_name)…
2026-09-29 12:04:02,098 - INFO - 🔍 Resolving 'Bacillus cereus' (type: species_name)
2026-09-29 12:04:02,361 - INFO -    Found TaxID 1396 for 'Bacillus cereus'
2026-09-29 12:04:03,372 - INFO -    ✅ GCF_059135435.1
2026-09-29 12:04:03,372 - INFO - [5/10778] Resolving 'Parabacteroides distasonis' (species_name)…
2026-09-29 12:04:03,372 - INFO - 🔍 Resolving 'Parabacteroides distasonis' (type: species_name)
2026-09-29 12:04:03,634 - INFO -    Found TaxID 823 for 'Parabacteroides distasonis'
2026-09-29 12:04:04,474 - INFO -    ✅ GCF_988232085.1
2026-09-29 12:04:04,474 - INFO - [6/10778] Resolving 'Dorea longicatena' (species_name)…
2026-09-29 12:04:04,474 - INFO - 🔍 Resolving 'Dorea longicatena' (type: species_name)
2026-09-29 12:04:04,787 - INFO -    Found TaxID 88431 for 'Dorea longicatena'
2026-09-29 12:04:05,352 - INFO -    ✅ GCF_988233105.1
2026-09-29 12:04:05,353 - INFO - [7/10778] Resolving 'Escherichia coli' (species_name)…
2026-09-29 12:04:05,353 - INFO - 🔍 Resolving 'Escherichia coli' (type: species_name)
2026-09-29 12:04:05,620 - INFO -    Found TaxID 562 for 'Escherichia coli'
2026-09-29 12:04:06,242 - INFO -    ✅ GCF_061253515.1
2026-09-29 12:04:06,242 - INFO - [8/10778] Resolving 'Staphylococcus epidermidis' (species_name)…
2026-09-29 12:04:06,242 - INFO - 🔍 Resolving 'Staphylococcus epidermidis' (type: species_name)
... (132024 more lines — increase max_lines to see all)

=== /pipeline-logs/logs/host_download_failures.log ===
  (not available yet)

In [8]:
# ── phage_host_candidates.csv ──────────────────────────────────────────────
candidates = load_csv(csv_dir / 'phage_host_candidates.csv')
if not candidates.empty:
    print('\nColumns:', candidates.columns.tolist())
    display(candidates.head(10))
    
    print('\n--- Token type distribution ---')
    if 'Token_Type' in candidates.columns:
        display(candidates['Token_Type'].value_counts().rename('count'))
    
    print(f'\nUnique phages : {candidates["Phage_ID"].nunique():,}')
    print(f'Total tokens  : {len(candidates):,}')

[phage_host_candidates.csv] 1,356,533 rows × 5 columns

Columns: ['Phage_ID', 'Host_Raw', 'Host_Token', 'Token_Type', 'Token_Order']

,Phage_ID,Host_Raw,Host_Token,Token_Type,Token_Order
0,1111525849475051:k141_1295821_length_55304_cov_50.0000,Xylella fastidiosa,Xylella fastidiosa,species_name,1
1,1111525849475051:k141_659940_length_33502_cov_36.9752,Corynebacterium xerosis,Corynebacterium xerosis,species_name,1
2,1111525849475064:k141_1333017_length_3534_cov_29.0000,Salmonella enterica,Salmonella enterica,species_name,1
3,1111525849475830:k141_1051363_length_7863_cov_530.0000,Salmonella enterica,Salmonella enterica,species_name,1
4,1111525849475830:k141_1337912_length_7654_cov_66.0000,Bacillus cereus,Bacillus cereus,species_name,1
5,1111525849475830:k141_1720558_length_67458_cov_45.5609,Parabacteroides distasonis,Parabacteroides distasonis,species_name,1
6,1111525849475830:k141_1916821_length_3751_cov_51.0000,Dorea longicatena,Dorea longicatena,species_name,1
7,1111525849475830:k141_2058922_length_7592_cov_133.0178,Bacillus cereus,Bacillus cereus,species_name,1
8,1111525849475830:k141_2213952_length_7409_cov_41.0056,Salmonella enterica,Salmonella enterica,species_name,1
9,1111525849475830:k141_227495_length_7588_cov_936.0000,Salmonella enterica,Salmonella enterica,species_name,1

--- Token type distribution ---

Token_Type
species_name          1021163
other                  327766
assembly_accession       7604
Name: count, dtype: int64

Unique phages : 1,310,154
Total tokens  : 1,356,533

In [9]:
# ── phage_host_assemblies.csv ──────────────────────────────────────────────
assemblies = load_csv(csv_dir / 'phage_host_assemblies.csv')
if not assemblies.empty:
    print('\nColumns:', assemblies.columns.tolist())
    display(assemblies.head(10))

    if 'Resolution_Source' in assemblies.columns:
        print('\n--- Resolution source distribution ---')
        display(assemblies['Resolution_Source'].value_counts().rename('count'))

    if 'Ambiguous' in assemblies.columns:
        n_amb = assemblies['Ambiguous'].sum()
        print(f'\nAmbiguous resolutions : {n_amb:,} / {len(assemblies):,}')

    if 'Assembly_Level' in assemblies.columns:
        print('\n--- Assembly level distribution ---')
        display(assemblies['Assembly_Level'].value_counts().rename('count'))

[phage_host_assemblies.csv] 1,252,249 rows × 14 columns

Columns: ['Phage_ID', 'Host_Raw', 'Host_Token', 'Token_Type', 'Token_Order', 'Assembly_Accession', 'Resolution_Source', 'Resolution_Rank', 'Confidence', 'Assembly_Level', 'RefSeq_Category', 'Quality_Score', 'Ambiguous', 'Ambiguity_Reason']

,Phage_ID,Host_Raw,Host_Token,Token_Type,Token_Order,Assembly_Accession,Resolution_Source,Resolution_Rank,Confidence,Assembly_Level,RefSeq_Category,Quality_Score,Ambiguous,Ambiguity_Reason
0,1111525849475051:k141_1295821_length_55304_cov_50.0000,Xylella fastidiosa,Xylella fastidiosa,species_name,1,GCF_055959565.1,species_to_taxid_to_assembly,1,0.7,Complete Genome,na,1010,False,NaN
1,1111525849475051:k141_659940_length_33502_cov_36.9752,Corynebacterium xerosis,Corynebacterium xerosis,species_name,1,GCF_055583525.1,species_to_taxid_to_assembly,1,0.7,Scaffold,na,110,False,NaN
2,1111525849475064:k141_1333017_length_3534_cov_29.0000,Salmonella enterica,Salmonella enterica,species_name,1,GCF_061253545.1,species_to_taxid_to_assembly,1,0.7,Complete Genome,na,1010,False,NaN
3,1111525849475830:k141_1051363_length_7863_cov_530.0000,Salmonella enterica,Salmonella enterica,species_name,1,GCF_061253545.1,species_to_taxid_to_assembly,1,0.7,Complete Genome,na,1010,False,NaN
4,1111525849475830:k141_1337912_length_7654_cov_66.0000,Bacillus cereus,Bacillus cereus,species_name,1,GCF_059135435.1,species_to_taxid_to_assembly,1,0.7,Complete Genome,na,1010,False,NaN
5,1111525849475830:k141_1720558_length_67458_cov_45.5609,Parabacteroides distasonis,Parabacteroides distasonis,species_name,1,GCF_988232085.1,species_to_taxid_to_assembly,1,0.7,Complete Genome,na,1010,False,NaN
6,1111525849475830:k141_1916821_length_3751_cov_51.0000,Dorea longicatena,Dorea longicatena,species_name,1,GCF_988233105.1,species_to_taxid_to_assembly,1,0.7,Complete Genome,na,1010,False,NaN
7,1111525849475830:k141_2058922_length_7592_cov_133.0178,Bacillus cereus,Bacillus cereus,species_name,1,GCF_059135435.1,species_to_taxid_to_assembly,1,0.7,Complete Genome,na,1010,False,NaN
8,1111525849475830:k141_2213952_length_7409_cov_41.0056,Salmonella enterica,Salmonella enterica,species_name,1,GCF_061253545.1,species_to_taxid_to_assembly,1,0.7,Complete Genome,na,1010,False,NaN
9,1111525849475830:k141_227495_length_7588_cov_936.0000,Salmonella enterica,Salmonella enterica,species_name,1,GCF_061253545.1,species_to_taxid_to_assembly,1,0.7,Complete Genome,na,1010,False,NaN

--- Resolution source distribution ---

Resolution_Source
species_to_taxid_to_assembly    963918
fallback                        280727
accession_in_host_field           7604
Name: count, dtype: int64

Ambiguous resolutions : 0 / 1,252,249

--- Assembly level distribution ---

Assembly_Level
Complete Genome    1137219
Scaffold             59625
Contig               45990
Chromosome            9415
Name: count, dtype: int64

In [10]:
# ── assembly_metadata.csv ─────────────────────────────────────────────────
asm_meta = load_csv(csv_dir / 'assembly_metadata.csv')
if not asm_meta.empty:
    print('\nColumns:', asm_meta.columns.tolist())
    display(asm_meta.head(10))

    if 'Download_Status' in asm_meta.columns:
        print('\n--- Download status distribution ---')
        display(asm_meta['Download_Status'].value_counts().rename('count'))

    if 'Metadata_Only' in asm_meta.columns:
        print(f'\nMetadata-only (no FASTA downloaded): {asm_meta["Metadata_Only"].sum():,}')

[assembly_metadata.csv] 5,521 rows × 17 columns

Columns: ['Assembly_Accession', 'Assembly_Name', 'Organism_Name', 'Species_TaxID', 'Strain', 'Assembly_Level', 'RefSeq_Category', 'BioSample', 'BioProject', 'FTP_Path', 'Submission_Date', 'Is_Latest', 'Quality_Score', 'Is_RefSeq', 'Download_Status', 'Download_Date', 'Metadata_Only']

,Assembly_Accession,Assembly_Name,Organism_Name,Species_TaxID,Strain,Assembly_Level,RefSeq_Category,BioSample,BioProject,FTP_Path,Submission_Date,Is_Latest,Quality_Score,Is_RefSeq,Download_Status,Download_Date,Metadata_Only
0,GCF_055959565.1,ASM5595956v1,Xylella fastidiosa,2371,-,Complete Genome,na,SAMN46769223,-,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/055/959/565/GCF_055959565.1_ASM55...,2026/03/18 00:00,True,1010,True,success,2026-09-29,False
1,GCF_055583525.1,ASM5558352v1,Corynebacterium xerosis,1725,-,Scaffold,na,SAMN55302120,-,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/055/583/525/GCF_055583525.1_ASM55...,2026/03/01 00:00,True,110,True,success,2026-09-29,False
2,GCF_061253545.1,ASM6125354v1,Salmonella enterica,28901,-,Complete Genome,na,SAMD01824296,-,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/061/253/545/GCF_061253545.1_ASM61...,2026/09/17 00:00,True,1010,True,success,2026-09-29,False
3,GCF_059135435.1,ASM5913543v1,Bacillus cereus,1396,-,Complete Genome,na,SAMN41670791,-,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/059/135/435/GCF_059135435.1_ASM59...,2026/07/11 00:00,True,1010,True,success,2026-09-29,False
4,GCF_988232085.1,AF120-97-WCA,Parabacteroides distasonis,823,-,Complete Genome,na,SAMEA123409535,-,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/988/232/085/GCF_988232085.1_AF120...,2026/09/12 00:00,True,1010,True,success,2026-09-29,False
5,GCF_988233105.1,AF120-90-WCA_contig_2_np1,Dorea longicatena,88431,-,Complete Genome,na,SAMEA123409528,-,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/988/233/105/GCF_988233105.1_AF120...,2026/09/12 00:00,True,1010,True,success,2026-09-29,False
6,GCF_061253515.1,ASM6125351v1,Escherichia coli,562,-,Complete Genome,na,SAMD01824297,-,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/061/253/515/GCF_061253515.1_ASM61...,2026/09/17 00:00,True,1010,True,success,2026-09-29,False
7,GCF_060343455.1,ASM6034345v1,Staphylococcus epidermidis,1282,-,Complete Genome,na,SAMN41748931,-,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/060/343/455/GCF_060343455.1_ASM60...,2026/08/24 00:00,True,1010,True,success,2026-09-29,False
8,GCF_059428005.1,ASM5942800v1,Corynebacterium striatum,43770,-,Complete Genome,na,SAMN61220267,-,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/059/428/005/GCF_059428005.1_ASM59...,2026/07/15 00:00,True,1010,True,success,2026-09-29,False
9,GCF_039728355.1,ASM3972835v1,Burkholderia cenocepacia,95486,-,Complete Genome,na,SAMN41377768,-,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/039/728/355/GCF_039728355.1_ASM39...,2024/05/24 00:00,True,1010,True,success,2026-09-29,False

--- Download status distribution ---

Download_Status
success         5507
failed            10
stats_failed       4
Name: count, dtype: int64

Metadata-only (no FASTA downloaded): 0

In [11]:
# ── host_metadata.csv ────────────────────────────────────────────────────
host_meta = load_csv(csv_dir / 'host_metadata.csv')
if not host_meta.empty:
    print('\nColumns:', host_meta.columns.tolist())
    display(host_meta.head(10))

[host_metadata.csv] 5,521 rows × 11 columns

Columns: ['Host_ID', 'Species_Name', 'Strain_Name', 'Assembly_Accession', 'Assembly_Name', 'Assembly_Level', 'Genome_Length', 'GC_Content', 'RefSeq_Category', 'Download_Date', 'Source']

,Host_ID,Species_Name,Strain_Name,Assembly_Accession,Assembly_Name,Assembly_Level,Genome_Length,GC_Content,RefSeq_Category,Download_Date,Source
0,GCF_055959565_1,Xylella fastidiosa,-,GCF_055959565.1,ASM5595956v1,Complete Genome,2619904,52.09,na,2026-09-29,assembly_resolver
1,GCF_055583525_1,Corynebacterium xerosis,-,GCF_055583525.1,ASM5558352v1,Scaffold,2708450,69.6,na,2026-09-29,assembly_resolver
2,GCF_061253545_1,Salmonella enterica,-,GCF_061253545.1,ASM6125354v1,Complete Genome,4831550,52.11,na,2026-09-29,assembly_resolver
3,GCF_059135435_1,Bacillus cereus,-,GCF_059135435.1,ASM5913543v1,Complete Genome,5789343,35.08,na,2026-09-29,assembly_resolver
4,GCF_988232085_1,Parabacteroides distasonis,-,GCF_988232085.1,AF120-97-WCA,Complete Genome,5075596,45.14,na,2026-09-29,assembly_resolver
5,GCF_988233105_1,Dorea longicatena,-,GCF_988233105.1,AF120-90-WCA_contig_2_np1,Complete Genome,3316380,41.39,na,2026-09-29,assembly_resolver
6,GCF_061253515_1,Escherichia coli,-,GCF_061253515.1,ASM6125351v1,Complete Genome,5612115,50.4,na,2026-09-29,assembly_resolver
7,GCF_060343455_1,Staphylococcus epidermidis,-,GCF_060343455.1,ASM6034345v1,Complete Genome,2534423,32.23,na,2026-09-29,assembly_resolver
8,GCF_059428005_1,Corynebacterium striatum,-,GCF_059428005.1,ASM5942800v1,Complete Genome,3018083,59.13,na,2026-09-29,assembly_resolver
9,GCF_039728355_1,Burkholderia cenocepacia,-,GCF_039728355.1,ASM3972835v1,Complete Genome,8270568,66.71,na,2026-09-29,assembly_resolver

In [12]:
# ── phage_host_links.csv ─────────────────────────────────────────────────
links = load_csv(csv_dir / 'phage_host_links.csv')
if not links.empty:
    print('\nColumns:', links.columns.tolist())
    display(links.head(10))
    print(f'\nUnique phages with a host link : {links["Phage_ID"].nunique():,}')

[phage_host_links.csv] 1,243,727 rows × 7 columns

Columns: ['Phage_ID', 'Host_Species', 'Host_Full_Name', 'Assembly_Accession', 'Assembly_Level', 'RefSeq_Category', 'Link_Quality']

,Phage_ID,Host_Species,Host_Full_Name,Assembly_Accession,Assembly_Level,RefSeq_Category,Link_Quality
0,1111525849475051:k141_1295821_length_55304_cov_50.0000,Xylella fastidiosa,Xylella fastidiosa,GCF_055959565.1,Complete Genome,na,direct
1,1111525849475051:k141_659940_length_33502_cov_36.9752,Corynebacterium xerosis,Corynebacterium xerosis,GCF_055583525.1,Scaffold,na,direct
2,1111525849475064:k141_1333017_length_3534_cov_29.0000,Salmonella enterica,Salmonella enterica,GCF_061253545.1,Complete Genome,na,direct
3,1111525849475830:k141_1051363_length_7863_cov_530.0000,Salmonella enterica,Salmonella enterica,GCF_061253545.1,Complete Genome,na,direct
4,1111525849475830:k141_1337912_length_7654_cov_66.0000,Bacillus cereus,Bacillus cereus,GCF_059135435.1,Complete Genome,na,direct
5,1111525849475830:k141_1720558_length_67458_cov_45.5609,Parabacteroides distasonis,Parabacteroides distasonis,GCF_988232085.1,Complete Genome,na,direct
6,1111525849475830:k141_1916821_length_3751_cov_51.0000,Dorea longicatena,Dorea longicatena,GCF_988233105.1,Complete Genome,na,direct
7,1111525849475830:k141_2058922_length_7592_cov_133.0178,Bacillus cereus,Bacillus cereus,GCF_059135435.1,Complete Genome,na,direct
8,1111525849475830:k141_2213952_length_7409_cov_41.0056,Salmonella enterica,Salmonella enterica,GCF_061253545.1,Complete Genome,na,direct
9,1111525849475830:k141_227495_length_7588_cov_936.0000,Salmonella enterica,Salmonella enterica,GCF_061253545.1,Complete Genome,na,direct

Unique phages with a host link : 1,221,717

In [13]:
# ── host_token_resolution_cache.json ────────────────────────────────────
cache_path = csv_dir / 'host_token_resolution_cache.json'
if cache_path.exists():
    with cache_path.open('r') as fh:
        cache = json.load(fh)
    n_tokens = len(cache)
    n_resolved = sum(1 for v in cache.values() if v)
    n_empty = n_tokens - n_resolved
    print(f'Token resolution cache: {n_tokens:,} tokens total')
    print(f'  Resolved (≥1 assembly) : {n_resolved:,}')
    print(f'  Empty (no assembly)    : {n_empty:,}')
else:
    print('host_token_resolution_cache.json not available yet.')

Token resolution cache: 10,778 tokens total
  Resolved (≥1 assembly) : 6,221
  Empty (no assembly)    : 4,557

---
<a id='5-host-mapping'></a>
## 5 — Host Mapping Creation

Rule: `create_host_mapping` (script: `create_host_mapping.py`)

Builds a `Host_ID → FASTA path` JSON from the downloaded assemblies and any private host data.

> Log file: `logs/create_host_mapping.log`

In [14]:
show_log(logs_dir / 'create_host_mapping.log')

=== /pipeline-logs/logs/create_host_mapping.log ===
2026-09-30 00:50:28,535 - INFO - ======================================================================
2026-09-30 00:50:28,535 - INFO - 🚀 Starting host mapping creation
2026-09-30 00:50:28,535 - INFO -    Metadata CSV    : /pipeline-logs/csv/host_metadata.csv
2026-09-30 00:50:28,536 - INFO -    Private mapping : /private-data/private_host_fasta_mapping.json
2026-09-30 00:50:28,536 - INFO -    Input dir       : /data/intermediate/fasta/hosts
2026-09-30 00:50:28,536 - INFO -    Output          : /data/processed/sequences/host_fasta_mapping.json
2026-09-30 00:50:28,553 - INFO -    Host rows in CSV: 5521
2026-09-30 00:50:28,567 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_988226545_1.fna
2026-09-30 00:50:28,585 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_988226305_1.fna
2026-09-30 00:50:28,588 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_988226485_1.fna
2026-09-30 00:50:28,595 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_000312665_1.fna
2026-09-30 00:50:28,597 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_988243195_1.fna
2026-09-30 00:50:28,603 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_977232545_1.fna
2026-09-30 00:50:28,603 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_009905255_1.fna
2026-09-30 00:50:28,723 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_988281115_1.fna
2026-09-30 00:50:28,844 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_988277545_1.fna
2026-09-30 00:50:28,858 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_061342815_1.fna
2026-09-30 00:50:28,892 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCF_987699915_1.fna
2026-09-30 00:50:28,901 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCA_002491635_1.fna
2026-09-30 00:50:28,903 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCA_002358615_1.fna
2026-09-30 00:50:28,903 - WARNING - ⚠️  Missing or empty file: /data/intermediate/fasta/hosts/GCA_002359915_1.fna
2026-09-30 00:50:28,903 - WARNING - ⚠️  14 host file(s) were missing or empty (e.g. /data/intermediate/fasta/hosts/GCF_988226545_1.fna)
2026-09-30 00:50:28,932 - INFO - ✅ Created mapping for 5507 public host FASTA files
2026-09-30 00:50:28,932 - INFO - ✅ Added 3 private host FASTA files
2026-09-30 00:50:28,932 - WARNING - ⚠️  14 host file(s) were missing or empty
2026-09-30 00:50:28,932 - INFO -    Total hosts in mapping : 5510
2026-09-30 00:50:28,932 - INFO -    Elapsed                : 0.4s
2026-09-30 00:50:28,933 - INFO - ======================================================================

---
<a id='6-host-qc'></a>
## 6 — Host FASTA QC & Indexing

Rule: `index_individual_host_sequences` (script: `index_individual_hosts.py`)

QC procedure per host FASTA (non-destructive):
1. **Header audit**: files with duplicate sequence identifiers are *rejected* (not indexed).
2. **Sequence content audit**: identical sequences trigger a warning but the file is still indexed.

**Outputs**
| File | Description |
|------|-------------|
| `logs/index_individual_host_sequences.log` | Step-by-step execution log |
| `logs/host_fasta_qc.csv` | Per-file QC results (DataFrame-loadable) |

In [15]:
show_log(logs_dir / 'index_individual_host_sequences.log')

=== /pipeline-logs/logs/index_individual_host_sequences.log ===
Total host FASTA files: 5510
Newly indexed: 5507
Already indexed (skipped): 3
Rejected (duplicate headers): 0
Errors: 0

QC log: /pipeline-logs/logs/host_fasta_qc.csv
2026-09-30 00:55:51,366 - INFO - Indexing complete: 5507 newly indexed, 3 pre-existing, 0 rejected, 0 errors

In [16]:
# ── host_fasta_qc.csv ─────────────────────────────────────────────────────
qc = load_csv(logs_dir / 'host_fasta_qc.csv')
if not qc.empty:
    print('\nColumns:', qc.columns.tolist())
    display(qc.head(10))

    if 'index_status' in qc.columns:
        print('\n--- Index status distribution ---')
        display(qc['index_status'].value_counts().rename('count'))

    if 'header_qc_status' in qc.columns:
        print('\n--- Header QC status distribution ---')
        display(qc['header_qc_status'].value_counts().rename('count'))

    if 'seq_qc_status' in qc.columns:
        print('\n--- Sequence QC status distribution ---')
        display(qc['seq_qc_status'].value_counts().rename('count'))

    # Rejected files (duplicate headers)
    if 'index_status' in qc.columns:
        rejected = qc[qc['index_status'] == 'rejected_duplicate_headers']
        if not rejected.empty:
            print(f'\n--- Rejected files ({len(rejected):,}) ---')
            display(rejected[['host_id', 'n_duplicate_headers',
                               'duplicate_header_examples', 'error_message']].head(20))

    # Files with duplicate sequences (warning)
    if 'n_identical_seq_groups' in qc.columns:
        dup_seq = qc[qc['n_identical_seq_groups'].fillna(0) > 0]
        if not dup_seq.empty:
            print(f'\n--- Files with duplicate sequences ({len(dup_seq):,}) ---')
            display(dup_seq[['host_id', 'n_identical_seq_groups',
                              'identical_seq_group_examples']].head(20))

[host_fasta_qc.csv] 5,507 rows × 12 columns

Columns: ['host_id', 'fasta_path', 'index_existed', 'total_sequences', 'header_qc_status', 'n_duplicate_headers', 'duplicate_header_examples', 'seq_qc_status', 'n_identical_seq_groups', 'identical_seq_group_examples', 'index_status', 'error_message']

,host_id,fasta_path,index_existed,total_sequences,header_qc_status,n_duplicate_headers,duplicate_header_examples,seq_qc_status,n_identical_seq_groups,identical_seq_group_examples,index_status,error_message
0,GCF_055959565_1,/data/intermediate/fasta/hosts/GCF_055959565_1.fna,False,1,ok,0,NaN,ok,0,NaN,indexed,NaN
1,GCF_055583525_1,/data/intermediate/fasta/hosts/GCF_055583525_1.fna,False,8,ok,0,NaN,ok,0,NaN,indexed,NaN
2,GCF_061253545_1,/data/intermediate/fasta/hosts/GCF_061253545_1.fna,False,2,ok,0,NaN,ok,0,NaN,indexed,NaN
3,GCF_059135435_1,/data/intermediate/fasta/hosts/GCF_059135435_1.fna,False,4,ok,0,NaN,ok,0,NaN,indexed,NaN
4,GCF_988232085_1,/data/intermediate/fasta/hosts/GCF_988232085_1.fna,False,10,ok,0,NaN,ok,0,NaN,indexed,NaN
5,GCF_988233105_1,/data/intermediate/fasta/hosts/GCF_988233105_1.fna,False,1,ok,0,NaN,ok,0,NaN,indexed,NaN
6,GCF_061253515_1,/data/intermediate/fasta/hosts/GCF_061253515_1.fna,False,4,ok,0,NaN,ok,0,NaN,indexed,NaN
7,GCF_060343455_1,/data/intermediate/fasta/hosts/GCF_060343455_1.fna,False,3,ok,0,NaN,ok,0,NaN,indexed,NaN
8,GCF_059428005_1,/data/intermediate/fasta/hosts/GCF_059428005_1.fna,False,1,ok,0,NaN,ok,0,NaN,indexed,NaN
9,GCF_039728355_1,/data/intermediate/fasta/hosts/GCF_039728355_1.fna,False,5,ok,0,NaN,ok,0,NaN,indexed,NaN

--- Index status distribution ---

index_status
indexed    5507
Name: count, dtype: int64

--- Header QC status distribution ---

header_qc_status
ok    5507
Name: count, dtype: int64

--- Sequence QC status distribution ---

seq_qc_status
ok                             5504
warning_identical_sequences       3
Name: count, dtype: int64

--- Files with duplicate sequences (3) ---

,host_id,n_identical_seq_groups,identical_seq_group_examples
632,GCF_000245735_1,2,"NZ_AHTH01000061.1 Alishewanella jeotgali KCTC 22429 contig061, whole genome ..."
1686,GCF_001046895_1,1,"NZ_CAQI01000016.1 Pseudarthrobacter siccitolerans strain 4J27, whole genome ..."
1903,GCF_001431085_1,1,"NZ_BBRU01000548.1 Candidatus Symbiothrix dinenymphae strain C5-4h, whole gen..."

---
<a id='7-host-status'></a>
## 7 — Host Status Report

Rule: `create_host_status_report` (script: `create_host_status_report.py`)

Joins the four upstream tables (candidates, assemblies, assembly_metadata, QC log)
into a single per-`(Phage_ID, Host_Token)` summary.

**Outputs**
| File | Description |
|------|-------------|
| `logs/create_host_status_report.log` | Step-by-step log |
| `reports/host_status_report.csv` | Combined status table |

In [17]:
show_log(logs_dir / 'create_host_status_report.log')

=== /pipeline-logs/logs/create_host_status_report.log ===
2026-09-30 00:55:52,809 - INFO - 📋 Loading upstream tables…
2026-09-30 00:55:55,327 - INFO -    candidates: 1356533 rows
2026-09-30 00:55:57,582 - INFO -    assemblies: 1252249 rows
2026-09-30 00:55:57,602 - INFO -    assembly_metadata: 5521 rows
2026-09-30 00:55:57,612 - INFO -    qc_log: 5507 rows
2026-09-30 00:56:13,834 - INFO - ============================================================
2026-09-30 00:56:13,834 - INFO - HOST STATUS REPORT SUMMARY
2026-09-30 00:56:13,834 - INFO - ============================================================
2026-09-30 00:56:13,834 - INFO - Total phages:                    1310154
2026-09-30 00:56:13,834 - INFO - Phages with ≥1 resolved host:    1221717
2026-09-30 00:56:13,834 - INFO - Assemblies downloaded:             5507
2026-09-30 00:56:13,834 - INFO - Assemblies indexed:                5507
2026-09-30 00:56:13,834 - INFO - Assemblies rejected (dup hdrs):       0
2026-09-30 00:56:13,834 - INFO - Output: /pipeline-logs/reports/host_status_report.csv
2026-09-30 00:56:13,834 - INFO - ============================================================

In [18]:
# ── host_status_report.csv ───────────────────────────────────────────────
status_report = load_csv(rep_dir / 'host_status_report.csv')
if not status_report.empty:
    print('\nColumns:', status_report.columns.tolist())
    display(status_report.head(10))

    # Key summary metrics
    n_phages  = status_report['Phage_ID'].nunique()
    print(f'\nTotal unique phages            : {n_phages:>8,}')

    if 'Resolution_Status' in status_report.columns:
        n_res = status_report.loc[
            status_report['Resolution_Status'] == 'resolved', 'Phage_ID'
        ].nunique()
        print(f'Phages with ≥1 resolved host   : {n_res:>8,}')
        print(f'Phages with no resolved host   : {n_phages - n_res:>8,}')

        print('\n--- Resolution status distribution ---')
        display(status_report['Resolution_Status'].value_counts().rename('rows'))

    if 'Download_Status' in status_report.columns:
        print('\n--- Download status distribution ---')
        display(status_report['Download_Status'].value_counts(dropna=False).rename('rows'))

    if 'index_status' in status_report.columns:
        print('\n--- Index status distribution ---')
        display(status_report['index_status'].value_counts(dropna=False).rename('rows'))

    # Assemblies with failed downloads
    if 'Download_Status' in status_report.columns:
        failures = status_report[
            status_report['Download_Status'].notna() &
            (status_report['Download_Status'] != 'success')
        ].drop_duplicates('Assembly_Accession')
        if not failures.empty:
            cols = [c for c in ['Assembly_Accession', 'Organism_Name', 'Strain',
                                 'Download_Status'] if c in failures.columns]
            print(f'\n--- Download failures ({len(failures):,} assemblies) ---')
            display(failures[cols].head(20))

[host_status_report.csv] 1,356,533 rows × 29 columns

Columns: ['Phage_ID', 'Host_Raw', 'Host_Token', 'Token_Type', 'Token_Order', 'Assembly_Accession', 'Resolution_Source', 'Resolution_Rank', 'Confidence', 'Assembly_Level', 'RefSeq_Category', 'Quality_Score', 'Ambiguous', 'Ambiguity_Reason', 'Resolution_Status', 'Download_Status', 'Download_Date', 'Metadata_Only', 'Organism_Name', 'Strain', 'total_sequences', 'header_qc_status', 'n_duplicate_headers', 'duplicate_header_examples', 'seq_qc_status', 'n_identical_seq_groups', 'identical_seq_group_examples', 'index_status', 'error_message']

,Phage_ID,Host_Raw,Host_Token,Token_Type,Token_Order,Assembly_Accession,Resolution_Source,Resolution_Rank,Confidence,Assembly_Level,RefSeq_Category,Quality_Score,Ambiguous,Ambiguity_Reason,Resolution_Status,Download_Status,Download_Date,Metadata_Only,Organism_Name,Strain,total_sequences,header_qc_status,n_duplicate_headers,duplicate_header_examples,seq_qc_status,n_identical_seq_groups,identical_seq_group_examples,index_status,error_message
0,1111525849475051:k141_1295821_length_55304_cov_50.0000,Xylella fastidiosa,Xylella fastidiosa,species_name,1,GCF_055959565.1,species_to_taxid_to_assembly,1.0,0.7,Complete Genome,na,1010.0,False,NaN,resolved,success,2026-09-29,False,Xylella fastidiosa,-,1.0,ok,0.0,NaN,ok,0.0,NaN,indexed,NaN
1,1111525849475051:k141_659940_length_33502_cov_36.9752,Corynebacterium xerosis,Corynebacterium xerosis,species_name,1,GCF_055583525.1,species_to_taxid_to_assembly,1.0,0.7,Scaffold,na,110.0,False,NaN,resolved,success,2026-09-29,False,Corynebacterium xerosis,-,8.0,ok,0.0,NaN,ok,0.0,NaN,indexed,NaN
2,1111525849475064:k141_1333017_length_3534_cov_29.0000,Salmonella enterica,Salmonella enterica,species_name,1,GCF_061253545.1,species_to_taxid_to_assembly,1.0,0.7,Complete Genome,na,1010.0,False,NaN,resolved,success,2026-09-29,False,Salmonella enterica,-,2.0,ok,0.0,NaN,ok,0.0,NaN,indexed,NaN
3,1111525849475830:k141_1051363_length_7863_cov_530.0000,Salmonella enterica,Salmonella enterica,species_name,1,GCF_061253545.1,species_to_taxid_to_assembly,1.0,0.7,Complete Genome,na,1010.0,False,NaN,resolved,success,2026-09-29,False,Salmonella enterica,-,2.0,ok,0.0,NaN,ok,0.0,NaN,indexed,NaN
4,1111525849475830:k141_1337912_length_7654_cov_66.0000,Bacillus cereus,Bacillus cereus,species_name,1,GCF_059135435.1,species_to_taxid_to_assembly,1.0,0.7,Complete Genome,na,1010.0,False,NaN,resolved,success,2026-09-29,False,Bacillus cereus,-,4.0,ok,0.0,NaN,ok,0.0,NaN,indexed,NaN
5,1111525849475830:k141_1720558_length_67458_cov_45.5609,Parabacteroides distasonis,Parabacteroides distasonis,species_name,1,GCF_988232085.1,species_to_taxid_to_assembly,1.0,0.7,Complete Genome,na,1010.0,False,NaN,resolved,success,2026-09-29,False,Parabacteroides distasonis,-,10.0,ok,0.0,NaN,ok,0.0,NaN,indexed,NaN
6,1111525849475830:k141_1916821_length_3751_cov_51.0000,Dorea longicatena,Dorea longicatena,species_name,1,GCF_988233105.1,species_to_taxid_to_assembly,1.0,0.7,Complete Genome,na,1010.0,False,NaN,resolved,success,2026-09-29,False,Dorea longicatena,-,1.0,ok,0.0,NaN,ok,0.0,NaN,indexed,NaN
7,1111525849475830:k141_2058922_length_7592_cov_133.0178,Bacillus cereus,Bacillus cereus,species_name,1,GCF_059135435.1,species_to_taxid_to_assembly,1.0,0.7,Complete Genome,na,1010.0,False,NaN,resolved,success,2026-09-29,False,Bacillus cereus,-,4.0,ok,0.0,NaN,ok,0.0,NaN,indexed,NaN
8,1111525849475830:k141_2213952_length_7409_cov_41.0056,Salmonella enterica,Salmonella enterica,species_name,1,GCF_061253545.1,species_to_taxid_to_assembly,1.0,0.7,Complete Genome,na,1010.0,False,NaN,resolved,success,2026-09-29,False,Salmonella enterica,-,2.0,ok,0.0,NaN,ok,0.0,NaN,indexed,NaN
9,1111525849475830:k141_227495_length_7588_cov_936.0000,Salmonella enterica,Salmonella enterica,species_name,1,GCF_061253545.1,species_to_taxid_to_assembly,1.0,0.7,Complete Genome,na,1010.0,False,NaN,resolved,success,2026-09-29,False,Salmonella enterica,-,2.0,ok,0.0,NaN,ok,0.0,NaN,indexed,NaN

Total unique phages            : 1,310,154
Phages with ≥1 resolved host   : 1,221,717
Phages with no resolved host   :   88,437

--- Resolution status distribution ---

Resolution_Status
resolved      1252249
unresolved     104284
Name: rows, dtype: int64

--- Download status distribution ---

Download_Status
success         1248490
NaN              104284
failed             3696
stats_failed         63
Name: rows, dtype: int64

--- Index status distribution ---

index_status
indexed    1248490
NaN         108043
Name: rows, dtype: int64

--- Download failures (14 assemblies) ---

,Assembly_Accession,Organism_Name,Strain,Download_Status
3069,GCF_988226545.1,Rhodococcoides fascians,-,failed
118146,GCF_988226305.1,Paraburkholderia aspalathi,-,failed
125138,GCF_988226485.1,Rahnella victoriana,-,failed
125842,GCF_000312665.1,Rhizobium mesoamericanum,-,stats_failed
125938,GCF_988243195.1,Citrobacter portucalensis,-,stats_failed
126428,GCF_977232545.1,Croceibacter atlanticus,-,stats_failed
126469,GCF_009905255.1,Thermoanaerobacterium aotearoense,-,stats_failed
177172,GCF_988281115.1,Kushneria sp. SRL386,-,failed
1019840,GCF_988277545.1,Desulfovibrio sp.,-,failed
1043010,GCF_061342815.1,Leptospira levettii,-,failed
1077921,GCF_987699915.1,Amycolatopsis sp.,-,failed
1189232,GCA_002491635.1,Bacteroides sp. UBA7156,-,failed
1223510,GCA_002358615.1,Porphyromonadaceae bacterium UBA3400,-,failed
1331144,GCA_002359915.1,Anaerococcus sp. UBA2626,-,failed

---
<a id='8-fasta-merge'></a>
## 8 — Phage & Protein FASTA Merging

Rules: `merge_phage_fasta` and `merge_protein_fasta` (script: `merge_fasta.py`)

Merges per-source FASTA files into a single combined FASTA for phages and proteins.

> Log files: `logs/merge_phage_fasta.log`, `logs/merge_protein_fasta.log`

In [19]:
show_log(logs_dir / 'merge_phage_fasta.log')

=== /pipeline-logs/logs/merge_phage_fasta.log ===
2026-09-29 12:03:13,335 - INFO - ======================================================================
2026-09-29 12:03:13,335 - INFO - 🚀 Starting phage FASTA merge
2026-09-29 12:03:13,335 - INFO -    Expected inputs : 26
2026-09-29 12:03:13,335 - INFO -    Output          : /data/processed/sequences/all_phages.fasta
2026-09-29 12:03:13,335 - INFO -    Valid inputs    : 26/26
2026-09-29 12:46:22,228 - INFO - 📊 Per-source phage counts:
2026-09-29 12:46:22,432 - INFO -                  MetaVR:      225,269
2026-09-29 12:46:22,432 - INFO -                    GOV2:      195,699
2026-09-29 12:46:22,432 - INFO -                     MGV:      189,680
2026-09-29 12:46:22,432 - INFO -                   IMGVR:      177,361
2026-09-29 12:46:22,432 - INFO -                     GPD:      142,809
2026-09-29 12:46:22,432 - INFO -                  TemPhD:       66,823
2026-09-29 12:46:22,432 - INFO -                    ELGV:       56,716
2026-09-29 12:46:22,432 - INFO -                    CHVD:       44,935
2026-09-29 12:46:22,433 - INFO -                    URPC:       44,633
2026-09-29 12:46:22,433 - INFO -               TYMEFLIES:       44,192
2026-09-29 12:46:22,433 - INFO -                     OVD:       37,184
2026-09-29 12:46:22,433 - INFO -                     GVD:       31,402
2026-09-29 12:46:22,433 - INFO -                    UHGV:       21,176
2026-09-29 12:46:22,433 - INFO -                    BAPS:       18,590
2026-09-29 12:46:22,433 - INFO -                     OPD:       14,649
2026-09-29 12:46:22,433 - INFO -                    IGVD:       10,021
2026-09-29 12:46:22,433 - INFO -                  RefSeq:        4,637
2026-09-29 12:46:22,433 - INFO -                     GSV:        4,518
2026-09-29 12:46:22,434 - INFO -                     STV:        4,065
2026-09-29 12:46:22,434 - INFO -                    HPGC:        3,872
2026-09-29 12:46:22,434 - INFO -                PhagesDB:        3,754
2026-09-29 12:46:22,434 - INFO -                    VMGC:        3,485
2026-09-29 12:46:22,434 - INFO -                     SVD:        2,634
2026-09-29 12:46:22,434 - INFO -                 Genbank:        2,085
2026-09-29 12:46:22,434 - INFO -                    DDBJ:          290
2026-09-29 12:46:22,434 - INFO -                    EMBL:          156
2026-09-29 12:46:22,434 - INFO -                   TOTAL:    1,350,635
2026-09-29 12:46:22,434 - INFO - ✅ Merged 26/26 phage FASTA files
2026-09-29 12:46:22,435 - INFO -    Output size     : 54,005,996,268 bytes
2026-09-29 12:46:22,435 - INFO -    Elapsed         : 2589.1s
2026-09-29 12:46:22,435 - INFO - ======================================================================

In [20]:
show_log(logs_dir / 'merge_protein_fasta.log')

=== /pipeline-logs/logs/merge_protein_fasta.log ===
2026-09-29 16:05:11,907 - INFO - ======================================================================
2026-09-29 16:05:11,907 - INFO - 🚀 Starting protein FASTA merge
2026-09-29 16:05:11,908 - INFO -    Expected inputs : 26
2026-09-29 16:05:11,908 - INFO -    Output          : /data/processed/sequences/all_proteins.fasta
2026-09-29 16:05:11,908 - INFO -    Valid inputs    : 26/26
2026-09-29 16:51:31,753 - INFO - 📊 Per-source protein counts:
2026-09-29 16:51:31,754 - INFO -                  MetaVR:   15,554,208
2026-09-29 16:51:31,754 - INFO -                   IMGVR:   12,036,448
2026-09-29 16:51:31,754 - INFO -                     MGV:   10,517,011
2026-09-29 16:51:31,754 - INFO -                     GPD:    7,616,044
2026-09-29 16:51:31,754 - INFO -                    GOV2:    5,189,318
2026-09-29 16:51:31,754 - INFO -                  TemPhD:    3,465,586
2026-09-29 16:51:31,754 - INFO -               TYMEFLIES:    2,858,218
2026-09-29 16:51:31,754 - INFO -                    URPC:    2,677,938
2026-09-29 16:51:31,754 - INFO -                    CHVD:    1,945,943
2026-09-29 16:51:31,755 - INFO -                    HPGC:    1,460,317
2026-09-29 16:51:31,755 - INFO -                     OVD:    1,331,603
2026-09-29 16:51:31,755 - INFO -                    UHGV:    1,224,355
2026-09-29 16:51:31,755 - INFO -                    ELGV:    1,220,565
2026-09-29 16:51:31,755 - INFO -                    BAPS:    1,108,519
2026-09-29 16:51:31,755 - INFO -                     OPD:      811,614
2026-09-29 16:51:31,755 - INFO -                     GVD:      746,146
2026-09-29 16:51:31,755 - INFO -                  RefSeq:      480,642
2026-09-29 16:51:31,755 - INFO -                     GSV:      352,027
2026-09-29 16:51:31,755 - INFO -                PhagesDB:      351,898
2026-09-29 16:51:31,755 - INFO -                    IGVD:      339,921
2026-09-29 16:51:31,755 - INFO -                 Genbank:      217,128
2026-09-29 16:51:31,755 - INFO -                    VMGC:      172,846
2026-09-29 16:51:31,755 - INFO -                     STV:      151,993
2026-09-29 16:51:31,755 - INFO -                     SVD:      110,417
2026-09-29 16:51:31,755 - INFO -                    DDBJ:       17,391
2026-09-29 16:51:31,755 - INFO -                    EMBL:       11,095
2026-09-29 16:51:31,755 - INFO -                   TOTAL:   71,969,191
2026-09-29 16:51:31,755 - INFO - ✅ Merged 26/26 protein FASTA files
2026-09-29 16:51:31,755 - INFO -    Output size     : 23,862,457,074 bytes
2026-09-29 16:51:31,755 - INFO -    Elapsed         : 2779.8s
2026-09-29 16:51:31,755 - INFO - ======================================================================

---
<a id='9-fasta-index'></a>
## 9 — Phage & Protein FASTA Indexing

Rules: `index_phage_sequences` and `index_protein_sequences` (script: `index_sequences.py`)

Each step:
1. Normalises and deduplicates sequences in place.
2. Creates a pyfaidx `.fai` index.
3. Writes a duplicate analysis HTML report to `reports/`.

> Log files: `logs/index_phage_sequences.log`, `logs/index_protein_sequences.log`  
> HTML reports: `reports/{fasta_name}_duplicates.html`

In [21]:
show_log(logs_dir / 'index_phage_sequences.log')

=== /pipeline-logs/logs/index_phage_sequences.log ===
2026-09-29 12:47:51,836 - INFO - 🚀 Starting FASTA indexing
2026-09-29 12:47:51,836 - INFO - 📂 Input: /data/processed/sequences/all_phages.fasta
2026-09-29 12:47:51,836 - INFO - 📂 Output: /data/processed/sequences/all_phages.fasta.fai
2026-09-29 12:47:57,856 - INFO - 💾 Available memory: 481.1 GB / 503.3 GB
2026-09-29 12:47:57,865 - INFO - 📦 Input file size: 50.30 GB
2026-09-29 12:47:57,865 - INFO - 🔍 Validating basic FASTA format
2026-09-29 12:47:57,865 - INFO - 🔧 Step 1: Normalizing and deduplicating FASTA (in-place)
2026-09-29 12:47:57,865 - INFO - ⚠️  This will modify the original file: /data/processed/sequences/all_phages.fasta
2026-09-29 12:47:57,865 - INFO - 🔧 Normalizing and deduplicating FASTA: /data/processed/sequences/all_phages.fasta
2026-09-29 12:47:57,865 - INFO - 📋 Using canonical key (is_protein=False): token0 (Phage_ID)
2026-09-29 12:56:28,821 - INFO -    📊 Processed 100,000 sequences, kept 100,000...
2026-09-29 13:01:40,298 - INFO -    📊 Processed 200,000 sequences, kept 200,000...
2026-09-29 13:05:07,617 - INFO -    📊 Processed 300,000 sequences, kept 300,000...
2026-09-29 13:12:23,451 - INFO -    📊 Processed 400,000 sequences, kept 400,000...
2026-09-29 13:13:15,947 - INFO -    📊 Processed 500,000 sequences, kept 500,000...
2026-09-29 13:21:32,816 - INFO -    📊 Processed 600,000 sequences, kept 600,000...
2026-09-29 13:24:16,662 - INFO -    📊 Processed 700,000 sequences, kept 700,000...
2026-09-29 13:25:53,451 - INFO -    📊 Processed 800,000 sequences, kept 800,000...
2026-09-29 13:27:11,284 - INFO -    📊 Processed 900,000 sequences, kept 900,000...
2026-09-29 13:29:50,103 - INFO -    📊 Processed 1,000,000 sequences, kept 1,000,000...
2026-09-29 13:48:58,995 - INFO -    📊 Processed 1,100,000 sequences, kept 1,100,000...
2026-09-29 13:49:25,459 - INFO -    📊 Processed 1,200,000 sequences, kept 1,187,570...
2026-09-29 13:50:02,930 - INFO -    📊 Processed 1,300,000 sequences, kept 1,277,715...
2026-09-29 13:50:17,487 - INFO - 🔄 Replacing original with normalized file
2026-09-29 13:50:31,029 - INFO - ✅ Normalization complete:
2026-09-29 13:50:31,029 - INFO -    📊 Total sequences read: 1,350,635
2026-09-29 13:50:31,029 - INFO -    ✅ Sequences written: 1,327,915
2026-09-29 13:50:31,029 - INFO -    🗑️ Duplicates removed (identical): 22,720
2026-09-29 13:50:31,029 - INFO -    ⚠️ Duplicates skipped (different): 0
2026-09-29 13:50:31,030 - INFO -    🔑 Unique IDs with duplicates: 22,720
2026-09-29 13:50:31,044 - INFO -    📝 Duplicate report saved: /pipeline-logs/reports/all_phages_duplicates.html
2026-09-29 13:50:31,149 - INFO - ✅ Normalization complete
2026-09-29 13:50:31,149 - INFO -    Sequences written: 1,327,915
2026-09-29 13:50:31,149 - INFO -    Duplicates removed: 22,720
2026-09-29 13:50:31,149 - INFO -    Duplicates skipped: 0
2026-09-29 13:50:31,149 - INFO - 🔧 Step 2: Creating index
2026-09-29 13:50:31,149 - INFO - 🔍 Validating FASTA file: /data/processed/sequences/all_phages.fasta
2026-09-29 13:50:31,150 - INFO - ✅ FASTA file validation passed: /data/processed/sequences/all_phages.fasta
2026-09-29 13:50:31,150 - INFO - 📇 Creating index for: /data/processed/sequences/all_phages.fasta
2026-09-29 13:50:31,150 - INFO -    Using canonical phage key: token0 (Phage_ID)
2026-09-29 13:55:13,564 - INFO - ✅ Successfully indexed 1,327,915 sequences
2026-09-29 13:55:13,564 - INFO - 📊 Estimated total length: ~78,787,613,755 bp
2026-09-29 13:55:13,565 - INFO - 📁 Index file size: 84,814,403 bytes
2026-09-29 13:55:13,763 - INFO - 🔍 Sample sequence headers:
2026-09-29 13:55:13,763 - INFO -    - 'AE002163.1'
2026-09-29 13:55:13,763 - INFO -    - 'AF009630.1'
2026-09-29 13:55:13,763 - INFO -    - 'AF011378.1'
2026-09-29 13:55:13,763 - INFO -    - 'AF020713.1'
2026-09-29 13:55:13,763 - INFO -    - 'AF022214.1'
2026-09-29 13:55:13,763 - INFO - ✅ Indexing complete!
... (5 more lines — increase max_lines to see all)

In [22]:
show_log(logs_dir / 'index_protein_sequences.log')

=== /pipeline-logs/logs/index_protein_sequences.log ===
2026-09-29 16:51:32,992 - INFO - 🚀 Starting FASTA indexing
2026-09-29 16:51:32,992 - INFO - 📂 Input: /data/processed/sequences/all_proteins.fasta
2026-09-29 16:51:32,992 - INFO - 📂 Output: /data/processed/sequences/all_proteins.fasta.fai
2026-09-29 16:51:33,024 - INFO - 💾 Available memory: 490.2 GB / 503.3 GB
2026-09-29 16:51:33,024 - INFO - 📦 Input file size: 22.22 GB
2026-09-29 16:51:33,024 - INFO - 🔍 Validating basic FASTA format
2026-09-29 16:51:33,024 - INFO - 🔧 Step 1: Normalizing and deduplicating FASTA (in-place)
2026-09-29 16:51:33,024 - INFO - ⚠️  This will modify the original file: /data/processed/sequences/all_proteins.fasta
2026-09-29 16:51:33,024 - INFO - 🔧 Normalizing and deduplicating FASTA: /data/processed/sequences/all_proteins.fasta
2026-09-29 16:51:33,024 - INFO - 📋 Using canonical key (is_protein=True): token1 (Protein_ID)
2026-09-29 16:51:33,520 - INFO -    📊 Processed 100,000 sequences, kept 100,000...
2026-09-29 16:51:34,019 - INFO -    📊 Processed 200,000 sequences, kept 200,000...
2026-09-29 16:51:34,495 - INFO -    📊 Processed 300,000 sequences, kept 300,000...
2026-09-29 16:51:34,980 - INFO -    📊 Processed 400,000 sequences, kept 400,000...
2026-09-29 16:51:35,450 - INFO -    📊 Processed 500,000 sequences, kept 500,000...
2026-09-29 16:51:35,931 - INFO -    📊 Processed 600,000 sequences, kept 600,000...
2026-09-29 16:51:36,445 - INFO -    📊 Processed 700,000 sequences, kept 700,000...
2026-09-29 16:51:36,923 - INFO -    📊 Processed 800,000 sequences, kept 800,000...
2026-09-29 16:51:37,404 - INFO -    📊 Processed 900,000 sequences, kept 900,000...
2026-09-29 16:51:37,886 - INFO -    📊 Processed 1,000,000 sequences, kept 1,000,000...
2026-09-29 16:51:38,373 - INFO -    📊 Processed 1,100,000 sequences, kept 1,100,000...
2026-09-29 16:51:38,863 - INFO -    📊 Processed 1,200,000 sequences, kept 1,200,000...
2026-09-29 16:51:39,360 - INFO -    📊 Processed 1,300,000 sequences, kept 1,300,000...
2026-09-29 16:51:39,919 - INFO -    📊 Processed 1,400,000 sequences, kept 1,400,000...
2026-09-29 16:51:40,820 - INFO -    📊 Processed 1,500,000 sequences, kept 1,500,000...
2026-09-29 16:51:41,310 - INFO -    📊 Processed 1,600,000 sequences, kept 1,600,000...
2026-09-29 16:51:41,799 - INFO -    📊 Processed 1,700,000 sequences, kept 1,700,000...
2026-09-29 16:51:42,287 - INFO -    📊 Processed 1,800,000 sequences, kept 1,800,000...
2026-09-29 16:51:42,776 - INFO -    📊 Processed 1,900,000 sequences, kept 1,900,000...
2026-09-29 16:51:43,266 - INFO -    📊 Processed 2,000,000 sequences, kept 2,000,000...
2026-09-29 16:51:43,762 - INFO -    📊 Processed 2,100,000 sequences, kept 2,100,000...
2026-09-29 16:51:44,258 - INFO -    📊 Processed 2,200,000 sequences, kept 2,200,000...
2026-09-29 16:51:45,509 - INFO -    📊 Processed 2,300,000 sequences, kept 2,300,000...
2026-09-29 16:51:46,013 - INFO -    📊 Processed 2,400,000 sequences, kept 2,400,000...
2026-09-29 16:51:46,513 - INFO -    📊 Processed 2,500,000 sequences, kept 2,500,000...
2026-09-29 16:51:47,517 - INFO -    📊 Processed 2,600,000 sequences, kept 2,600,000...
2026-09-29 16:51:48,018 - INFO -    📊 Processed 2,700,000 sequences, kept 2,700,000...
2026-09-29 16:51:48,642 - INFO -    📊 Processed 2,800,000 sequences, kept 2,800,000...
2026-09-29 16:51:49,133 - INFO -    📊 Processed 2,900,000 sequences, kept 2,900,000...
2026-09-29 16:51:49,624 - INFO -    📊 Processed 3,000,000 sequences, kept 3,000,000...
2026-09-29 16:51:50,119 - INFO -    📊 Processed 3,100,000 sequences, kept 3,100,000...
2026-09-29 16:51:50,613 - INFO -    📊 Processed 3,200,000 sequences, kept 3,200,000...
2026-09-29 16:51:51,106 - INFO -    📊 Processed 3,300,000 sequences, kept 3,300,000...
2026-09-29 16:51:51,597 - INFO -    📊 Processed 3,400,000 sequences, kept 3,400,000...
2026-09-29 16:51:52,497 - INFO -    📊 Processed 3,500,000 sequences, kept 3,500,000...
2026-09-29 16:51:52,991 - INFO -    📊 Processed 3,600,000 sequences, kept 3,600,000...
2026-09-29 16:51:53,923 - INFO -    📊 Processed 3,700,000 sequences, kept 3,700,000...
2026-09-29 16:51:54,419 - INFO -    📊 Processed 3,800,000 sequences, kept 3,800,000...
2026-09-29 16:51:54,916 - INFO -    📊 Processed 3,900,000 sequences, kept 3,900,000...
2026-09-29 16:51:55,419 - INFO -    📊 Processed 4,000,000 sequences, kept 4,000,000...
... (711 more lines — increase max_lines to see all)

In [23]:
# Duplicate analysis HTML reports (generated by index_sequences.py)
dup_reports = sorted(rep_dir.glob('*_duplicates.html')) if rep_dir.exists() else []
if dup_reports:
    print('Duplicate analysis reports:')
    for p in dup_reports:
        print(f'  ✅  {p.name}  ({p.stat().st_size:,} B)')
else:
    print('No duplicate analysis reports found yet.')

Duplicate analysis reports:
  ✅  all_phages_duplicates.html  (349,955 B)
  ✅  all_proteins_duplicates.html  (352,815 B)

--- <a id='10-provenance-private'></a>
## 10 — Provenance and Private-Validation Diagnostics

This section helps diagnose source/provenance issues and missing private sources.

In [24]:
# ── Public provenance manifests ─────────────────────────────────────────────
pub_manifest_csv = load_csv(csv_dir / 'public_data_manifest.csv')
if not pub_manifest_csv.empty:
    cols = [c for c in ['feature', 'source_key', 'status', 'error_message', 'provider_release', 'provider_snapshot_date', 'provider_schema_profile'] if c in pub_manifest_csv.columns]
    display(pub_manifest_csv[cols].head(30))

    if 'status' in pub_manifest_csv.columns:
        print('Provenance status counts:')
        print(pub_manifest_csv['status'].value_counts(dropna=False))

        failed_rows = pub_manifest_csv[pub_manifest_csv['status'] != 'success']
        if len(failed_rows) > 0:
            print('[WARN] Non-success provenance rows:')
            display(failed_rows[cols])

run_prov_csv = load_csv(csv_dir / 'pipeline_run_provenance.csv')
if not run_prov_csv.empty:
    display(run_prov_csv.head(10))

# ── Private-source validation manifest ─────────────────────────────────────
private_manifest_candidates = [
    Path('/private-data/private_manifest.json'),
    Path.cwd().parent / 'private_data' / 'private_manifest.json',
    Path.cwd() / 'private_data' / 'private_manifest.json',
]
private_manifest = None
for candidate in private_manifest_candidates:
    if candidate.exists():
        private_manifest = candidate
        break

if private_manifest is None:
    print('[INFO] private_manifest.json not found in expected locations.')
else:
    print(f'Using private manifest: {private_manifest}')
    try:
        payload = json.loads(private_manifest.read_text())
    except json.JSONDecodeError as e:
        print(f"[WARN] Could not parse private manifest JSON: {e}")
        payload = {}

    print({k: payload.get(k) for k in ['sources_found', 'sources_valid', 'sources_invalid']})

    sources_df = pd.DataFrame(payload.get('sources', []))
    if not sources_df.empty:
        cols = [c for c in ['source_db', 'is_valid', 'source_dir', 'errors', 'warnings'] if c in sources_df.columns]
        display(sources_df[cols])

[public_data_manifest.csv] 229 rows × 18 columns

,feature,source_key,status,error_message,provider_release,provider_snapshot_date,provider_schema_profile
0,annotated_proteins_metadata,BAPS_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
1,annotated_proteins_metadata,CHVD_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
2,annotated_proteins_metadata,DDBJ_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
3,annotated_proteins_metadata,ELGV_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
4,annotated_proteins_metadata,EMBL_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
5,annotated_proteins_metadata,GOV2_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
6,annotated_proteins_metadata,GPD_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
7,annotated_proteins_metadata,GSV_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
8,annotated_proteins_metadata,GVD_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
9,annotated_proteins_metadata,Genbank_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
10,annotated_proteins_metadata,HPGC_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
11,annotated_proteins_metadata,IGVD_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
12,annotated_proteins_metadata,IMGVR_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
13,annotated_proteins_metadata,MGV_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
14,annotated_proteins_metadata,MetaVR_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
15,annotated_proteins_metadata,OPD_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
16,annotated_proteins_metadata,OVD_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
17,annotated_proteins_metadata,PhagesDB_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
18,annotated_proteins_metadata,RefSeq_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
19,annotated_proteins_metadata,STV_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
20,annotated_proteins_metadata,SVD_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
21,annotated_proteins_metadata,TYMEFLIES_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
22,annotated_proteins_metadata,TemPhD_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
23,annotated_proteins_metadata,UHGV_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
24,annotated_proteins_metadata,URPC_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
25,annotated_proteins_metadata,VMGC_Annotated_Proteins_metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
26,antimicrobial_resistance_gene_metadata,BAPS_Antimicrobial_Resistance_Gene_Metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
27,antimicrobial_resistance_gene_metadata,CHVD_Antimicrobial_Resistance_Gene_Metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
28,antimicrobial_resistance_gene_metadata,ELGV_Antimicrobial_Resistance_Gene_Metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2
29,antimicrobial_resistance_gene_metadata,GOV2_Antimicrobial_Resistance_Gene_Metadata_URL,success,NaN,rolling,2026-07-05,phagescope_v2

Provenance status counts:
status
success    217
failed      12
Name: count, dtype: int64
[WARN] Non-success provenance rows:

,feature,source_key,status,error_message,provider_release,provider_snapshot_date,provider_schema_profile
43,antimicrobial_resistance_gene_metadata,TYMEFLIES_Antimicrobial_Resistance_Gene_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
126,phage_transmembrane_protein_metadata,BAPS_Phage_Transmembrane_Protein_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
129,phage_transmembrane_protein_metadata,ELGV_Phage_Transmembrane_Protein_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
140,phage_transmembrane_protein_metadata,MetaVR_Phage_Transmembrane_Protein_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
141,phage_transmembrane_protein_metadata,OPD_Phage_Transmembrane_Protein_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
142,phage_transmembrane_protein_metadata,OVD_Phage_Transmembrane_Protein_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
146,phage_transmembrane_protein_metadata,SVD_Phage_Transmembrane_Protein_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
147,phage_transmembrane_protein_metadata,TYMEFLIES_Phage_Transmembrane_Protein_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
151,phage_transmembrane_protein_metadata,VMGC_Phage_Transmembrane_Protein_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
190,phage_virulent_factor_metadata,IMGVR_Phage_Virulent_Factor_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
196,phage_virulent_factor_metadata,STV_Phage_Virulent_Factor_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2
215,transcription_terminator_metadata,IMGVR_Phage_Transcription_Terminator_Metadata_URL,failed,HTTP Error 404: Not Found,rolling,2026-07-05,phagescope_v2

[pipeline_run_provenance.csv] 1 rows × 10 columns

,pipeline_run_timestamp,provider_name,provider_release,provider_snapshot_date,provider_schema_profile,provider_api_base_url,provider_provenance_mode,pbi_version,git_commit,download_records_count
0,2026-09-29T12:01:21Z,PhageScope,rolling,2026-07-05,phagescope_v2,https://phageapi.deepomics.org,config_pinned,NaN,NaN,229

Using private manifest: /private-data/private_manifest.json
{'sources_found': 1, 'sources_valid': 1, 'sources_invalid': 0}

      source_db  is_valid                  source_dir errors warnings
0  test_private      True  /private-data/test_private     []       []